apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-oas-config
  namespace: httpbin-staging
  labels:
    app: httpbin
data:
  httpbin-oas.json: |-
    {
      "openapi": "3.0.3",
      "info": {
        "title": "httpbin",
        "version": "1.0.0"
      },
      "paths": {
        "/get": {
          "get": {
            "operationId": "httpbinGet",
            "responses": {
              "200": {
                "description": "Success"
              }
            }
          }
        }
      },
      "components": {
        "securitySchemes": {
          "authToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
          }
        }
      },
      "security": [
        {
          "authToken": []
        }
      ],
      "x-tyk-api-gateway": {
        "info": {
          "name": "httpbin-api",
          "state": {
            "active": true
          }
        },
        "upstream": {
          "url": "http://httpbin.httpbin-staging.svc"
        },
        "server": {
          "listenPath": {
            "value": "/httpbin",
            "strip": true
          },
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "authToken": {
                "enabled": true
              }
            }
          }
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: httpbin-api
  namespace: httpbin-staging
  labels:
    app: httpbin
spec:
  tykOAS:
    configmapRef:
      name: httpbin-oas-config
      namespace: httpbin-staging
      keyName: httpbin-oas.json
